### ISSUE TITLE
Linux arm64 build

### ISSUE THREAD

**Issue by vladislavbagnyuk** [MarkusJx/node-java-bridge#26]
Hello,

could you please add pre-compiled binary for Linux on arm64 architecture? I'm currently trying to run it on Raspberry Pi 4 with 64-bit OS, bud I get an error that package java-bridge-linux-arm64-gnu was not found. I have tried to build it directly on the Raspberry Pi, but I don't know how to link resulting build to the library.

**Comment by vladislavbagnyuk** [comment]
If you could provide pre-compiled binaries for aarch64 that would be great. I've also compiled the package on a Raspberry Pi, but I don't know how to use the manually compiled binary with the library.

**Comment by MarkusJx** [comment]
Arm64 builds are now available since the latest release: [`v2.1.5-beta.1`](https://github.com/MarkusJx/node-java-bridge/releases/tag/v2.1.5-beta.1).
In order to install it, just run
```sh
npm install java-bridge@latest
```
This should automatically install the binaries for your system.

I tested the binaries on a Raspberry Pi 3B running a 64-bit version of Raspberry Pi OS based on Debian 11 (bullseye).
32-bit operating systems are not supported at the moment, but do let me know if you'd need this as well.

Also, please inform me if this works on your system, so I can close this issue and create a proper release

**Comment by vladislavbagnyuk** [comment]
Thank you! It's working.
